version: "3"
services:
 ssmongodb:
  image: mongo:latest
  container_name: "ssmongodb"
  ports:
  - 27101:27101
 springboot-mongodb:
  image: springboot-mongodb:1.0
  container_name: "springboot-mongodb"
  ports:
  - 8080:8080
  links:
  - ssmongodb